library(AnVIL)
library(dplyr)
samp = avtable(table="sample")
subj = avtable(table="subject")
seqtab = avtable(table="sequencing")
alltypes = unique(samp$`pfb:tissue_type`)
tissframes = lapply(na.omit(alltypes), function(x) samp |> filter(`pfb:tissue_type` == x)
names(tissframes) = na.omit(alltypes)
library(MultiAssayExperiment)
# by stages
t2 = lapply(tissframes, function(x) mutate(x, subject_id=`pfb:subject`))
t3 = lapply(t2, function(x) left_join(x, subj, by="subject_id"))
sqsq = mutate(seqtab, sample_id=`pfb:sample`)
t4 = lapply(t3, function(x) right_join(sqsq, x, by="sample_id"))
fullmeta = t4
GTExMAE = MultiAssayExperiment(ExperimentList(fullmeta))
